---
  - name: Host_Reboot
    tasks:
      - debug:
          msg: "Will reboot and then wait for {{ ansible_ssh_host }}:{{ ansible_ssh_port }} to come back to life"

      - name: Reboot system
          shell: sleep 2 && shutdown -r now "Ansible triggered reboot"
          async: 1
          poll: 0
          ignore_errors: true

      - name: Wait for system to boot up
          local_action: wait_for host={{ ansible_ssh_host }} port={{ ansible_ssh_port }} state=started delay=15 timeout=300
          become: False

      - debug:
            msg: "We're back again. Running on {{ inventory_hostname }}"

  - name: Host_Startup
      gather_facts: True
      tasks:
        - debug:
            msg: "Hello from Host_Startup on {{ inventory_hostname }}"
